version: "3"

services:
  db:
    container_name: tesior-postgres
    image: postgres
    command: -c 'max_connections=800'
    shm_size: 1gb
    restart: always
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 5G
    networks:
      - gateway
    ports:
      - "4000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: tesior-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis-data:/var/lib/redis/data

networks:
  gateway:
    name: tesior
