name = "indexer"
compatibility_date = "2024-07-14"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=<YOUR_API_KEY_HERE>"
AUTH_TOKEN="<YOUR_AUTH_TOKEN_HERE"
# DIRECT_DATABASE_URL=postgresql://root:root@localhost:4000/tesior-db
# AUTH_TOKEN='test'

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"